#!/usr/bin/env python3
"""gen_golden_ids.py -- turn a saanoTTS e2e_ids.bin (int32 Piper phoneme
ids, little-endian) into a small C header for embedding in a sketch.

The ids array is tiny (a few hundred bytes for one utterance) -- this is
NOT how you'd embed the ~680 KB model weights (those go on LittleFS/SPIFFS,
see extras/README.md). It's just enough to give examples/SpeakGolden
something to say without requiring a phonemizer on-device.

Usage:
  python3 extras/gen_golden_ids.py \\
    --ids ../../mcu/test/fixtures/en_us_r7/e2e_ids.bin \\
    --out ../examples/SpeakGolden/golden_ids.h \\
    --name SANOTTS_GOLDEN_IDS

Regenerate this whenever you swap in a different fixture/voice; the ids
are meaningless without the matching front_q8.bin/model_q8.bin pair (same
voice, same phoneme vocabulary).
"""
from __future__ import annotations

import argparse
import struct
from pathlib import Path


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ids", required=True, help="path to an e2e_ids.bin (int32 LE phoneme ids)")
    ap.add_argument("--out", required=True, help="output .h path")
    ap.add_argument("--name", default="SANOTTS_GOLDEN_IDS", help="C array name (default: %(default)s)")
    a = ap.parse_args()

    data = Path(a.ids).read_bytes()
    if len(data) % 4 != 0:
        raise SystemExit(f"{a.ids}: size {len(data)} is not a multiple of 4 (not int32 LE ids)")
    n = len(data) // 4
    ids = struct.unpack(f"<{n}i", data)

    lines = [
        "/* Auto-generated by extras/gen_golden_ids.py -- do not edit by hand.",
        f" * Source: {a.ids}",
        f" * {n} Piper phoneme ids for one golden-fixture utterance",
        " * (voice: en_US Kristin r7, the same voice as the shipped model_q8.bin/",
        " * front_q8.bin fixture -- these ids are meaningless with any other voice's",
        " * phoneme vocabulary). */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define {a.name}_N {n}",
        f"static const int32_t {a.name}[{a.name}_N] = {{",
    ]
    for i in range(0, n, 16):
        row = ", ".join(str(x) for x in ids[i:i + 16])
        lines.append(f"  {row},")
    lines.append("};")
    lines.append("")

    out_path = Path(a.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path} ({n} ids)")


if __name__ == "__main__":
    main()
