/* generated by export_fsd_golden.py -- do not edit */
#pragma once

#define FSD_IN_CH 192
#define FSD_ENC_HIDDEN 64
#define FSD_CODE_DIM 40
#define FSD_DIM 76
#define FSD_BLOCKS 5
#define FSD_FILM_RANK 12
#define FSD_HEAD_RANK 48
#define FSD_N_FFT 1024
#define FSD_BINS 513
#define FSD_HOP 256
#define FSD_DW_KERNEL 7
#define FSD_PW_HIDDEN 304

#define OFF_ENC0_W 0 /* 12288 floats */
#define OFF_ENC0_B 12288 /* 64 floats */
#define OFF_ENC1_W 12352 /* 2560 floats */
#define OFF_ENC1_B 14912 /* 40 floats */
#define OFF_PRE_W 14952 /* 3040 floats */
#define OFF_PRE_B 17992 /* 76 floats */
#define OFF_B0_DW_W 18068 /* 532 floats */
#define OFF_B0_DW_B 18600 /* 76 floats */
#define OFF_B0_NORM_W 18676 /* 76 floats */
#define OFF_B0_NORM_B 18752 /* 76 floats */
#define OFF_B0_FILMR_W 18828 /* 480 floats */
#define OFF_B0_FILMR_B 19308 /* 12 floats */
#define OFF_B0_FILMO_W 19320 /* 1824 floats */
#define OFF_B0_FILMO_B 21144 /* 152 floats */
#define OFF_B0_PW0_W 21296 /* 23104 floats */
#define OFF_B0_PW0_B 44400 /* 304 floats */
#define OFF_B0_PW1_W 44704 /* 23104 floats */
#define OFF_B0_PW1_B 67808 /* 76 floats */
#define OFF_B0_SCALE 67884 /* 1 floats */
#define OFF_B1_DW_W 67885 /* 532 floats */
#define OFF_B1_DW_B 68417 /* 76 floats */
#define OFF_B1_NORM_W 68493 /* 76 floats */
#define OFF_B1_NORM_B 68569 /* 76 floats */
#define OFF_B1_FILMR_W 68645 /* 480 floats */
#define OFF_B1_FILMR_B 69125 /* 12 floats */
#define OFF_B1_FILMO_W 69137 /* 1824 floats */
#define OFF_B1_FILMO_B 70961 /* 152 floats */
#define OFF_B1_PW0_W 71113 /* 23104 floats */
#define OFF_B1_PW0_B 94217 /* 304 floats */
#define OFF_B1_PW1_W 94521 /* 23104 floats */
#define OFF_B1_PW1_B 117625 /* 76 floats */
#define OFF_B1_SCALE 117701 /* 1 floats */
#define OFF_B2_DW_W 117702 /* 532 floats */
#define OFF_B2_DW_B 118234 /* 76 floats */
#define OFF_B2_NORM_W 118310 /* 76 floats */
#define OFF_B2_NORM_B 118386 /* 76 floats */
#define OFF_B2_FILMR_W 118462 /* 480 floats */
#define OFF_B2_FILMR_B 118942 /* 12 floats */
#define OFF_B2_FILMO_W 118954 /* 1824 floats */
#define OFF_B2_FILMO_B 120778 /* 152 floats */
#define OFF_B2_PW0_W 120930 /* 23104 floats */
#define OFF_B2_PW0_B 144034 /* 304 floats */
#define OFF_B2_PW1_W 144338 /* 23104 floats */
#define OFF_B2_PW1_B 167442 /* 76 floats */
#define OFF_B2_SCALE 167518 /* 1 floats */
#define OFF_B3_DW_W 167519 /* 532 floats */
#define OFF_B3_DW_B 168051 /* 76 floats */
#define OFF_B3_NORM_W 168127 /* 76 floats */
#define OFF_B3_NORM_B 168203 /* 76 floats */
#define OFF_B3_FILMR_W 168279 /* 480 floats */
#define OFF_B3_FILMR_B 168759 /* 12 floats */
#define OFF_B3_FILMO_W 168771 /* 1824 floats */
#define OFF_B3_FILMO_B 170595 /* 152 floats */
#define OFF_B3_PW0_W 170747 /* 23104 floats */
#define OFF_B3_PW0_B 193851 /* 304 floats */
#define OFF_B3_PW1_W 194155 /* 23104 floats */
#define OFF_B3_PW1_B 217259 /* 76 floats */
#define OFF_B3_SCALE 217335 /* 1 floats */
#define OFF_B4_DW_W 217336 /* 532 floats */
#define OFF_B4_DW_B 217868 /* 76 floats */
#define OFF_B4_NORM_W 217944 /* 76 floats */
#define OFF_B4_NORM_B 218020 /* 76 floats */
#define OFF_B4_FILMR_W 218096 /* 480 floats */
#define OFF_B4_FILMR_B 218576 /* 12 floats */
#define OFF_B4_FILMO_W 218588 /* 1824 floats */
#define OFF_B4_FILMO_B 220412 /* 152 floats */
#define OFF_B4_PW0_W 220564 /* 23104 floats */
#define OFF_B4_PW0_B 243668 /* 304 floats */
#define OFF_B4_PW1_W 243972 /* 23104 floats */
#define OFF_B4_PW1_B 267076 /* 76 floats */
#define OFF_B4_SCALE 267152 /* 1 floats */
#define OFF_HEAD_IN_W 267153 /* 3648 floats */
#define OFF_HEAD_IN_B 270801 /* 48 floats */
#define OFF_HEAD_OUT_W 270849 /* 73872 floats */
#define OFF_HEAD_OUT_B 344721 /* 1539 floats */

#define FSD_MODEL_FLOATS 346260
