/* GENERATED by esphome/tools/gen_component_data.py -- do not edit.
 *
 * Source lineage: en_us_e12nano (294,642 params, 24 kHz, hop 256).
 * This is a SIBLING of the `heart-nano` voice, NOT the same weights;
 * never attach a measurement taken with this data to heart-nano's name.
 *
 * SPDX-License-Identifier: MIT (sanoTTS inference runtime, see LICENSE.MIT)
 */

#pragma once

#include <stdint.h>

/* The on-chip correctness gate and the memory ladder both come from
 * mcu/test/fixtures/en_us_e12nano/. Gates (BOARDS.md): corr > 0.98 and
 * 0.80 < rms_ratio < 1.25 against SANOTTS_R00_AUDIO, which is the FLOAT
 * PyTorch stack's waveform -- so this is the model gate, not merely a
 * port gate.
 *
 * Durations are frozen (rNN_durs.bin) and fed through
 * snt_nano_config.dur_override: a one-frame drift in any token would
 * shift every later sample and make the correlation meaningless.
 *
 * A shorter row is a plain PREFIX of ids AND durs taken together -- that
 * is exactly how mcu/test/fixtures/en_us_e12nano_short was cut (verified:
 * its 51 ids and 51 durs are byte-identical to r00's first 51).
 */

#ifdef __cplusplus
extern "C" {
#endif

/* The arena cost model.
 *
 * It used to be a LINE: 49,264 B + 192.0 B/frame, DEVICE-measured on an
 * ESP32-S3 on 2026-09-09 from three fully-staged ladder rows (93, 192 and 281
 * frames -> 67,120, 86,128 and 103,216 B), with a step to 208 B/frame above
 * ~500 frames where the noise plane joined the peak phase. That slope was the
 * utterance-length ceiling: 3 s fitted the 122,880 B contiguous block ESPHome
 * leaves free, 4.4 s starved the weight staging and ran 3x slower, and 5.3 s
 * failed outright with rc=-2.
 *
 * snt_nano.c now runs the pipeline on FIXED-WIDTH windows (NANO_FRAME_CHUNK
 * output frames plus the pipeline receptive field on each side) instead of
 * whole-utterance planes, so the slope is GONE: one number, the same for a
 * one-second announcement and a thirty-second one. HOST-REF until the ladder
 * below re-measures it on silicon.
 */
#define SANOTTS_ARENA_FIXED 84208
#define SANOTTS_ARENA_PER_FRAME 0

#define SANOTTS_SAMPLE_RATE 24000   /* nano_q8_meta: hop 256, 93.75 fps */
#define SANOTTS_HOP 256

#define SANOTTS_R00_ID "000001_i200"
#define SANOTTS_R00_TOKENS 73
#define SANOTTS_R00_FRAMES 415
#define SANOTTS_R00_SAMPLES 105984
#define SANOTTS_R00_SEED 2236265385529901705ULL
extern const int32_t SANOTTS_R00_IDS[73];
extern const int32_t SANOTTS_R00_DURS[73];
extern const float SANOTTS_R00_AUDIO[105984];

#define SANOTTS_R06_ID "000007_i1400"
#define SANOTTS_R06_TOKENS 107
#define SANOTTS_R06_FRAMES 629
#define SANOTTS_R06_SAMPLES 160768
#define SANOTTS_R06_SEED 14351038112024617452ULL
extern const int32_t SANOTTS_R06_IDS[107];
extern const int32_t SANOTTS_R06_DURS[107];

#ifdef __cplusplus
}
#endif
