/* GENERATED by esphome/tools/gen_component_data.py -- do not edit.
 *
 * Source lineage: en_us_e12nano (294,642 params, 24 kHz, hop 256).
 * This is a SIBLING of the `heart-nano` voice, NOT the same weights;
 * never attach a measurement taken with this data to heart-nano's name.
 *
 * SPDX-License-Identifier: MIT (sanoTTS inference runtime, see LICENSE.MIT)
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/* front_q8.bin  175456 B  sha256 ec5538b3bb079dcff880ed2dcbd94f2a7587669cf05ad44844dcca50dcb4273b */
extern const unsigned char SANOTTS_FRONT_BLOB[175456];
/* model_q8.bin  164224 B  sha256 5d7fef542537263392cac522daf10b0e5039309d7985ef4e74bdced06a583c97 */
extern const unsigned char SANOTTS_DEC_BLOB[164224];

#define SANOTTS_FRONT_BLOB_BYTES 175456
#define SANOTTS_DEC_BLOB_BYTES 164224

#ifdef __cplusplus
}
#endif
