#!/usr/bin/env python3
"""Generate the flash-resident C data for the sanoTTS ESPHome component.

Emits three files into components/sanotts/:

  sanotts_model_data.c/.h   the en_us_e12nano int8 weight blobs
                            (front_q8.bin + model_q8.bin), byte-for-byte from
                            mcu/test/fixtures/en_us_e12nano/.
  sanotts_golden.c/.h       the golden fixture rows used by the on-chip
                            correctness gate and by the memory ladder:
                            phoneme ids, frozen durations, and the float32
                            reference waveform the PyTorch stack produced.

Every array is `const` so it lands in .rodata (flash-XIP) rather than RAM, and
16-byte aligned because the PIE SIMD staging path copies out of it.

LINEAGE: these bytes are `en_us_e12nano` (294,642 params). That lineage is a
SIBLING of the `heart-nano` voice, not the same weights. Chip numbers measured
with this data belong to en_us_e12nano and must never be attributed to
heart-nano.

Run:  python3 esphome/tools/gen_component_data.py
"""

from __future__ import annotations

import datetime
import hashlib
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FIXTURE = ROOT / "mcu" / "test" / "fixtures" / "en_us_e12nano"
OUT = ROOT / "esphome" / "components" / "sanotts"

BANNER = (
    "/* GENERATED by esphome/tools/gen_component_data.py -- do not edit.\n"
    " *\n"
    " * Source lineage: en_us_e12nano (294,642 params, 24 kHz, hop 256).\n"
    " * This is a SIBLING of the `heart-nano` voice, NOT the same weights;\n"
    " * never attach a measurement taken with this data to heart-nano's name.\n"
    " *\n"
    " * SPDX-License-Identifier: MIT (sanoTTS inference runtime, see LICENSE.MIT)\n"
    " */\n"
)


def read_exact(path: Path) -> bytes:
    if not path.is_file():
        raise SystemExit(f"missing required fixture file: {path}")
    data = path.read_bytes()
    if not data:
        raise SystemExit(f"fixture file is empty: {path}")
    return data


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def emit_bytes(name: str, data: bytes) -> str:
    out = [f"const unsigned char {name}[{len(data)}] "
           f"__attribute__((aligned(16))) = {{"]
    for i in range(0, len(data), 24):
        chunk = data[i:i + 24]
        out.append("  " + "".join(f"0x{b:02x}," for b in chunk))
    out.append("};")
    return "\n".join(out)


def emit_i32(name: str, values: list[int]) -> str:
    out = [f"const int32_t {name}[{len(values)}] = {{"]
    for i in range(0, len(values), 16):
        out.append("  " + "".join(f"{v}," for v in values[i:i + 16]))
    out.append("};")
    return "\n".join(out)


def emit_f32(name: str, values: list[float]) -> str:
    out = [f"const float {name}[{len(values)}] "
           f"__attribute__((aligned(16))) = {{"]
    for i in range(0, len(values), 8):
        out.append("  " + "".join(f"{v!r}f," for v in values[i:i + 8]))
    out.append("};")
    return "\n".join(out)


def read_i32(path: Path) -> list[int]:
    data = read_exact(path)
    if len(data) % 4:
        raise SystemExit(f"{path}: length {len(data)} is not a multiple of 4")
    return list(struct.unpack(f"<{len(data)//4}i", data))


def read_f32(path: Path) -> list[float]:
    data = read_exact(path)
    if len(data) % 4:
        raise SystemExit(f"{path}: length {len(data)} is not a multiple of 4")
    return list(struct.unpack(f"<{len(data)//4}f", data))


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    stamp = datetime.date.today().isoformat()

    front = read_exact(FIXTURE / "front_q8.bin")
    model = read_exact(FIXTURE / "model_q8.bin")

    r00_ids = read_i32(FIXTURE / "r00_ids.bin")
    r00_durs = read_i32(FIXTURE / "r00_durs.bin")
    r00_audio = read_f32(FIXTURE / "r00_audio.bin")
    r06_ids = read_i32(FIXTURE / "r06_ids.bin")
    r06_durs = read_i32(FIXTURE / "r06_durs.bin")

    if len(r00_ids) != len(r00_durs):
        raise SystemExit("r00 ids/durs length mismatch")
    if len(r06_ids) != len(r06_durs):
        raise SystemExit("r06 ids/durs length mismatch")

    # rows.txt is the contract: row_id tokens frames samples seed
    rows = {}
    for line in read_exact(FIXTURE / "rows.txt").decode().splitlines():
        parts = line.split()
        if len(parts) != 5:
            raise SystemExit(f"malformed rows.txt line: {line!r}")
        rows[parts[0]] = (int(parts[1]), int(parts[2]), int(parts[3]), int(parts[4]))

    for row_id, ids, durs in (("000001_i200", r00_ids, r00_durs),
                              ("000007_i1400", r06_ids, r06_durs)):
        if row_id not in rows:
            raise SystemExit(f"rows.txt has no entry for {row_id}")
        tokens, frames, samples, _seed = rows[row_id]
        if tokens != len(ids):
            raise SystemExit(f"{row_id}: rows.txt says {tokens} tokens, ids file has {len(ids)}")
        if sum(durs) != frames:
            raise SystemExit(f"{row_id}: durations sum to {sum(durs)}, rows.txt says {frames}")
        if samples != (frames - 1) * 256:
            raise SystemExit(f"{row_id}: samples {samples} != (frames-1)*hop")

    r00_row = rows["000001_i200"]
    r06_row = rows["000007_i1400"]
    if len(r00_audio) != r00_row[2 + 0]:
        pass  # checked below against samples
    if len(r00_audio) != r00_row[2]:
        raise SystemExit(
            f"r00_audio.bin has {len(r00_audio)} samples, rows.txt says {r00_row[2]}")

    # ---- model data ----------------------------------------------------
    hdr = [BANNER, "#pragma once", "", "#ifdef __cplusplus",
           'extern "C" {', "#endif", ""]
    hdr.append(f"/* front_q8.bin  {len(front)} B  sha256 {sha256(front)} */")
    hdr.append(f"extern const unsigned char SANOTTS_FRONT_BLOB[{len(front)}];")
    hdr.append(f"/* model_q8.bin  {len(model)} B  sha256 {sha256(model)} */")
    hdr.append(f"extern const unsigned char SANOTTS_DEC_BLOB[{len(model)}];")
    hdr.append("")
    hdr.append(f"#define SANOTTS_FRONT_BLOB_BYTES {len(front)}")
    hdr.append(f"#define SANOTTS_DEC_BLOB_BYTES {len(model)}")
    hdr.append("")
    hdr += ["#ifdef __cplusplus", "}", "#endif", ""]
    (OUT / "sanotts_model_data.h").write_text("\n".join(hdr))

    body = [BANNER, f"/* generated {stamp} */", '#include "sanotts_model_data.h"', ""]
    body.append(emit_bytes("SANOTTS_FRONT_BLOB", front))
    body.append("")
    body.append(emit_bytes("SANOTTS_DEC_BLOB", model))
    body.append("")
    (OUT / "sanotts_model_data.c").write_text("\n".join(body))

    # ---- golden fixture ------------------------------------------------
    ghdr = [BANNER, "#pragma once", "", "#include <stdint.h>", "",
            "/* The on-chip correctness gate and the memory ladder both come from",
            " * mcu/test/fixtures/en_us_e12nano/. Gates (BOARDS.md): corr > 0.98 and",
            " * 0.80 < rms_ratio < 1.25 against SANOTTS_R00_AUDIO, which is the FLOAT",
            " * PyTorch stack's waveform -- so this is the model gate, not merely a",
            " * port gate.",
            " *",
            " * Durations are frozen (rNN_durs.bin) and fed through",
            " * snt_nano_config.dur_override: a one-frame drift in any token would",
            " * shift every later sample and make the correlation meaningless.",
            " *",
            " * A shorter row is a plain PREFIX of ids AND durs taken together -- that",
            " * is exactly how mcu/test/fixtures/en_us_e12nano_short was cut (verified:",
            " * its 51 ids and 51 durs are byte-identical to r00's first 51).",
            " */", "", "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    ghdr.append('/* The arena cost model.')
    ghdr.append(' *')
    ghdr.append(' * It used to be a LINE: 49,264 B + 192.0 B/frame, DEVICE-measured on an')
    ghdr.append(' * ESP32-S3 on 2026-09-09 from three fully-staged ladder rows (93, 192 and 281')
    ghdr.append(' * frames -> 67,120, 86,128 and 103,216 B), with a step to 208 B/frame above')
    ghdr.append(' * ~500 frames where the noise plane joined the peak phase. That slope was the')
    ghdr.append(' * utterance-length ceiling: 3 s fitted the 122,880 B contiguous block ESPHome')
    ghdr.append(' * leaves free, 4.4 s starved the weight staging and ran 3x slower, and 5.3 s')
    ghdr.append(' * failed outright with rc=-2.')
    ghdr.append(' *')
    ghdr.append(' * snt_nano.c now runs the pipeline on FIXED-WIDTH windows (NANO_FRAME_CHUNK')
    ghdr.append(' * output frames plus the pipeline receptive field on each side) instead of')
    ghdr.append(' * whole-utterance planes, so the slope is GONE: one number, the same for a')
    ghdr.append(' * one-second announcement and a thirty-second one. HOST-REF until the ladder')
    ghdr.append(' * below re-measures it on silicon.')
    ghdr.append(' */')
    ghdr.append('#define SANOTTS_ARENA_FIXED 84208')
    ghdr.append('#define SANOTTS_ARENA_PER_FRAME 0')
    ghdr.append("")
    ghdr.append(f"#define SANOTTS_SAMPLE_RATE 24000   /* nano_q8_meta: hop 256, 93.75 fps */")
    ghdr.append(f"#define SANOTTS_HOP 256")
    ghdr.append("")
    ghdr.append(f'#define SANOTTS_R00_ID "000001_i200"')
    ghdr.append(f"#define SANOTTS_R00_TOKENS {len(r00_ids)}")
    ghdr.append(f"#define SANOTTS_R00_FRAMES {r00_row[1]}")
    ghdr.append(f"#define SANOTTS_R00_SAMPLES {r00_row[2]}")
    ghdr.append(f"#define SANOTTS_R00_SEED {r00_row[3]}ULL")
    ghdr.append(f"extern const int32_t SANOTTS_R00_IDS[{len(r00_ids)}];")
    ghdr.append(f"extern const int32_t SANOTTS_R00_DURS[{len(r00_durs)}];")
    ghdr.append(f"extern const float SANOTTS_R00_AUDIO[{len(r00_audio)}];")
    ghdr.append("")
    ghdr.append(f'#define SANOTTS_R06_ID "000007_i1400"')
    ghdr.append(f"#define SANOTTS_R06_TOKENS {len(r06_ids)}")
    ghdr.append(f"#define SANOTTS_R06_FRAMES {r06_row[1]}")
    ghdr.append(f"#define SANOTTS_R06_SAMPLES {r06_row[2]}")
    ghdr.append(f"#define SANOTTS_R06_SEED {r06_row[3]}ULL")
    ghdr.append(f"extern const int32_t SANOTTS_R06_IDS[{len(r06_ids)}];")
    ghdr.append(f"extern const int32_t SANOTTS_R06_DURS[{len(r06_durs)}];")
    ghdr += ["", "#ifdef __cplusplus", "}", "#endif", ""]
    (OUT / "sanotts_golden.h").write_text("\n".join(ghdr))

    gbody = [BANNER, f"/* generated {stamp} */", '#include "sanotts_golden.h"', ""]
    gbody.append(emit_i32("SANOTTS_R00_IDS", r00_ids))
    gbody.append(emit_i32("SANOTTS_R00_DURS", r00_durs))
    gbody.append(emit_i32("SANOTTS_R06_IDS", r06_ids))
    gbody.append(emit_i32("SANOTTS_R06_DURS", r06_durs))
    gbody.append(emit_f32("SANOTTS_R00_AUDIO", r00_audio))
    gbody.append("")
    (OUT / "sanotts_golden.c").write_text("\n".join(gbody))

    total = len(front) + len(model) + 4 * (len(r00_ids) + len(r00_durs)
                                           + len(r06_ids) + len(r06_durs)) \
        + 4 * len(r00_audio)
    print(f"wrote sanotts_model_data.[ch] and sanotts_golden.[ch] into {OUT}")
    print(f"  front_q8   {len(front):>9} B  sha256 {sha256(front)[:16]}")
    print(f"  model_q8   {len(model):>9} B  sha256 {sha256(model)[:16]}")
    print(f"  r00 audio  {4*len(r00_audio):>9} B  ({len(r00_audio)} float32 samples)")
    print(f"  flash total{total:>9} B")
    return 0


if __name__ == "__main__":
    sys.exit(main())
