/* Auto-generated by extras/gen_golden_ids.py -- do not edit by hand.
 * Source: ../../mcu/test/fixtures/en_us_r7/e2e_ids.bin
 * 80 Piper phoneme ids for one golden-fixture utterance
 * (voice: en_US Kristin r7, the same voice as the shipped model_q8.bin/
 * front_q8.bin fixture -- these ids are meaningless with any other voice's
 * phoneme vocabulary). */
#pragma once
#include <stdint.h>

#define SANOTTS_GOLDEN_IDS_N 80
static const int32_t SANOTTS_GOLDEN_IDS[SANOTTS_GOLDEN_IDS_N] = {
  1, 0, 28, 0, 24, 0, 120, 0, 21, 0, 122, 0, 38, 0, 3, 0,
  88, 0, 120, 0, 21, 0, 122, 0, 17, 0, 3, 0, 120, 0, 14, 0,
  74, 0, 32, 0, 59, 0, 25, 0, 3, 0, 35, 0, 120, 0, 52, 0,
  26, 0, 3, 0, 35, 0, 74, 0, 41, 0, 3, 0, 50, 0, 3, 0,
  23, 0, 120, 0, 51, 0, 122, 0, 25, 0, 3, 0, 28, 0, 120, 0,
};
